# config/application.yml
GOOGLE_CLIENT_ID: 606269245936-1ma3e2005ucqkskf976iicq89sbbfd9t.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET: 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

KAKAO_CLIENT_ID: 22ff1f45124d99a71dbeaabc2dce511d